apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  namespace: tandoor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
