apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-static
  namespace: tandoor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
