apiVersion: v1
kind: Service
metadata:
  name: tandoor
  namespace: tandoor
spec:
  selector:
    app: tandoor
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
